#!/bin/bash

BASE_PATH=./base

HELM_ADDITIONAL_OPT=""

OVERLAY_VALUE_FILE="$2/values.yaml"
if [ -f "$OVERLAY_VALUE_FILE" ]; then
    HELM_ADDITIONAL_OPT="$HELM_ADDITIONAL_OPT -f $2/values.yaml"
fi

# Geneerate output from manifest files
helm template ./what-the-helm --name-template foo --namespace default -f $BASE_PATH/values.yaml $HELM_ADDITIONAL_OPT > $BASE_PATH/all.yaml

case $1 in

  apply)
    kustomize build $2 | kubectl apply -f -
    ;;

  delete)
    kustomize build $2 | kubectl delete -f -
    ;;

  *)
    echo -n "unknown command, only supported commands are apply, delete"
    exit 1
    ;;
esac
